import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from 'react-i18next'
import PageWrap from '../components/global/wraps/page'

const AboutUs: NextPage = () => {

    const {t} = useTranslation()

    return (
        <>
            <Head>
                <title>{t('menu.aboutUs')}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            
            <PageWrap>
                <div className="text-gray-500 dark:text-gray-200 px-4 md:px-0">{t('menu.aboutUs')}</div>
            </PageWrap>
        </>
    )
}

export default AboutUs