import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from 'react-i18next'

import PageWrap from '../components/global/wraps/page'
import BannerStart from '../components/user/home/bannerStart'
import Description from '../components/user/home/description'

const Home: NextPage = () => {

    const {t} = useTranslation()

    return (
        <>
            <Head>
                <title>{t('menu.home')}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <PageWrap>
                <BannerStart />
            </PageWrap>

            <Description />
        </>
    )
}

export default Home