import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from 'react-i18next'
import PageWrap from '../components/global/wraps/page'

const Terms: NextPage = () => {

    const {t} = useTranslation()

    return (
        <PageWrap>
            <Head>
                <title>{t('menu.terms')}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className="text-gray-500 dark:text-gray-200 px-4 md:px-0">{t('menu.terms')}</div>
        </PageWrap>
    )
}

export default Terms