import type { NextPage } from 'next'
import Head from 'next/head'
import { useTranslation } from 'react-i18next'

import PageWrap from '../../components/global/wraps/page'
import Statistics from '../../components/panel/main/statistics'

const Panel: NextPage & any = () => {

    const {t} = useTranslation()

    return (
        <PageWrap variant="panel">
            <Head>
                <title>{t('menu.userPanel')}</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <Statistics />

            <div className="pt-5 text-gray-500 dark:text-gray-300 text-justify leading-8">
                {t('panel.mainPage.text')}
            </div>
        </PageWrap>
    )
}

Panel.layout = 'panel'

export default Panel